# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb580854de3f0a0726faa1aec31839d2507cb42f4bd4c4839eac41392e7800209fb9c679c3a4ac26041ac1018981ca241d12e6e7b78978784204542c1d1e71a

test:
  secret_key_base: 9cc678ebab3a3233bf047d7d9ab166bab64d4666e4ae7559d5f11205dc867101b1dc2290a7b945bdfd18cc116316b9c20b9954527e94229913bfd9494a19f6f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
